name: Ballerina Build and Test

on:
  pull_request:
    branches:
      - main  # Trigger on PR targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

    #   # Step 2: Set up Ballerina
    #   - name: Set up Ballerina
    #     run: |
    #       curl -L https://dist.ballerina.io/downloads/ballerina-2201.4.1/ballerina-2201.4.1-linux-x86_64.tar.gz | tar -xz -C /usr/local/
    #       echo "Ballerina setup completed"


      - name: Ballerina Action
        uses: ballerina-platform/ballerina-action@2201.10.1

      - name: check version
        run: bal -v


      # Step 3: Build the Ballerina project
      - name: Build Ballerina project
        run: |
          cd your-ballerina-project-directory  # Navigate to your project folder (adjust as needed)
          /usr/local/ballerina-2201.4.1/bin/ballerina build

      # Step 4: Run tests
      - name: Run Ballerina tests
        run: |
          /usr/local/ballerina-2201.4.1/bin/ballerina test your-ballerina-project-directory

      # Step 5: (Optional) Linting and Static Code Analysis
      - name: Run Ballerina Linter
        run: |
          /usr/local/ballerina-2201.4.1/bin/ballerina lint your-ballerina-project-directory

