name: Build and Deploy React App

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Debug Directory Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -l
          ls -l ../../

      - name: Install Frontend Dependencies
        run: |
          if [ -d "Frontend" ]; then
            cd Frontend
            npm install
          else
            echo "Error: Frontend directory not found!"
            exit 1
          fi

      # Step 3: Install dependencies and build the React app
      - name: Build
        run: |
          cd Frontend
          npm run build
    
 
      # Step 6: Configure Nginx on the EC2 instance
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
  
        with:
          host: ${{ secrets.PUBLIC_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo -i

            # Ensure Nginx is installed
            sudo apt update

            # Check if Nginx is already installed
            if ! dpkg -l | grep -q nginx; then
                echo "Nginx is not installed. Installing..."
                sudo apt install -y nginx
                rm -rf /etc/nginx/sites-available/default
            else
                echo "Nginx is already installed. Skipping installation."
            fi
            mkdir -p /usr/share/nginx/html/dist

            # Configure Nginx
            
            # echo "server {
            #     listen 80;
            #     server_name 34.236.243.37;
            #     root /usr/share/nginx/html/dist;
            #     index index.html;

            #     location / {
            #         try_files \$uri \$uri/ /index.html;  # Corrected try_files
            #     }
            #     location /todo-service/todos {
            #         proxy_pass http://10.0.184.32;
            #     }
            # }" | sudo tee /etc/nginx/sites-available/to-do > /dev/null

            echo 'server {
                listen 80;
                server_name yasithmayura.me www.yasithmayura.me;

                # Redirect all HTTP traffic to HTTPS
                return 301 https://$host$request_uri;
            }


            server {
                listen 443 ssl;
                server_name yasithmayura.me www.yasithmayura.me;

                # SSL configuration
                ssl_certificate /etc/letsencrypt/live/yasithmayura.me/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/yasithmayura.me/privkey.pem;
                ssl_trusted_certificate /etc/letsencrypt/live/yasithmayura.me/chain.pem;

                # SSL optimization
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
                ssl_prefer_server_ciphers on;

                # Root and index
                root /usr/share/nginx/html/dist;
                index index.html;

                # Basic Nginx setup
                location / {
                    try_files $uri $uri/ /index.html;
                }

                location /todo-service/todos {
                    proxy_pass http://10.0.184.32:9090;
                }
            }' | sudo tee /etc/nginx/sites-available/to-do > /dev/null


            # Enable the configuration
            sudo ln -sf /etc/nginx/sites-available/to-do /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl reload nginx


        # Step 4: Transfer the `build` directory to the EC2 instance
      - name: scp action
        uses: c0c1/scp-action@v1.0
  
        with:
          src: ./Frontend/dist
          host: ${{ secrets.PUBLIC_EC2_HOST }}
          remote: ./
          port: 22
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

      # Step 5: Move build files
      - name: move build files
        uses: appleboy/ssh-action@v1.2.0
  
        with:
          host: ${{ secrets.PUBLIC_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ -d "/usr/share/nginx/html/dist" ]; then
             echo "Directory /usr/share/nginx/html/dist exists. Deleting it..."
             sudo rm -rf /usr/share/nginx/html/dist
             echo "Directory deleted."
             sudo mv ./dist /usr/share/nginx/html/
            else
             sudo mv ./dist /usr/share/nginx/html/
            fi

            # Enable the configuration
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl reload nginx

